# Generated by Django 6.0 on 2026-03-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='display_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', through='apms.RoleUser', to='apms.role'),
        ),
        migrations.AddConstraint(
            model_name='roleuser',
            constraint=models.UniqueConstraint(fields=('role', 'user'), name='unique_role_user'),
        ),
    ]
