# Generated by Django 6.0 on 2026-03-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apms', '0002_alter_role_display_name_alter_role_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roleuser',
            name='unique_role_user',
        ),
        migrations.AddConstraint(
            model_name='roleuser',
            constraint=models.UniqueConstraint(fields=('role', 'user'), name='unique_user_role'),
        ),
    ]
